// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxQm29IL1Gp6LkQxZ1UlyEq6AF1Y_jto',
    appId: '1:592441110274:web:453507dece4d0a70cddc1b',
    messagingSenderId: '592441110274',
    projectId: 'mealappmislab2',
    authDomain: 'mealappmislab2.firebaseapp.com',
    storageBucket: 'mealappmislab2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDsoAfPcpj2xO75fi5wglMwKffl75mPs',
    appId: '1:592441110274:android:520a1dee9f2ad90fcddc1b',
    messagingSenderId: '592441110274',
    projectId: 'mealappmislab2',
    storageBucket: 'mealappmislab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe8_WmuTkkYunH2JXqtHdO7t0CQ7ymH8k',
    appId: '1:592441110274:ios:dac0584421ea46fecddc1b',
    messagingSenderId: '592441110274',
    projectId: 'mealappmislab2',
    storageBucket: 'mealappmislab2.firebasestorage.app',
    iosBundleId: 'com.example.mealApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe8_WmuTkkYunH2JXqtHdO7t0CQ7ymH8k',
    appId: '1:592441110274:ios:dac0584421ea46fecddc1b',
    messagingSenderId: '592441110274',
    projectId: 'mealappmislab2',
    storageBucket: 'mealappmislab2.firebasestorage.app',
    iosBundleId: 'com.example.mealApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByxQm29IL1Gp6LkQxZ1UlyEq6AF1Y_jto',
    appId: '1:592441110274:web:8f9c2d52f613caa1cddc1b',
    messagingSenderId: '592441110274',
    projectId: 'mealappmislab2',
    authDomain: 'mealappmislab2.firebaseapp.com',
    storageBucket: 'mealappmislab2.firebasestorage.app',
  );
}
